### ISSUE TITLE
Add database integration

### ISSUE THREAD

**Issue by tanvijain13** [umkc-cs-451-2020-spring/semester-project-group-8#36]

**Comment by StrainedQuacking** [comment]
For the windows users at the very least, this string should work to establish the connection `"Data Source=localhost;Initial Catalog=commerce;Integrated Security=True"`

Might also work for Mac, although authentication could be different.

**Comment by tanvijain13** [comment]
Work in progress for the database integration in the dashboard page.

**Comment by tanvijain13** [comment]
Work in progress for database integration

**Comment by StrainedQuacking** [comment]
Base database integration was added. More features need to be added to extend this integration but those will be covered in other issues.
